import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const extensionRoot = resolve(import.meta.dirname, "..");
export const EXTENSION_ID = "firefox@favlock.app";
export const PRODUCTION_API_URL = "https://api.favlock.app";
export const PRODUCTION_DASHBOARD_URL = "https://vault.favlock.app/";

function validateUrl(value, name) {
  const url = new URL(value);
  if (url.username || url.password || url.search || url.hash || url.pathname !== "/" ||
      !(url.protocol === "https:" || (url.protocol === "http:" &&
        ["localhost", "127.0.0.1"].includes(url.hostname)))) {
    throw new Error(`${name} must be an HTTPS origin (HTTP is allowed on loopback).`);
  }
  return url.origin;
}

export async function configure({ target = "production", outputDirectory = extensionRoot, test = false } = {}) {
  if (!["production", "development"].includes(target)) throw new Error("Invalid Firefox build target.");
  const development = target === "development";
  const config = {
    target,
    dashboardUrl: `${validateUrl(development
      ? (test ? "http://localhost:4177" : process.env.FIREFOX_DASHBOARD_URL || "https://vault.favlock.localhost")
      : PRODUCTION_DASHBOARD_URL, "FIREFOX_DASHBOARD_URL")}/`,
    apiUrl: validateUrl(development
      ? (test ? "http://localhost:4180" : process.env.FIREFOX_API_URL || "https://api.favlock.localhost")
      : PRODUCTION_API_URL, "FIREFOX_API_URL"),
    extensionId: EXTENSION_ID,
  };
  await writeFile(resolve(outputDirectory, "config.generated.js"),
    `// Generated by the Firefox configure script.\nexport const GENERATED_FAVLOCK_CONFIG = Object.freeze(${JSON.stringify(config, null, 2)});\n`);
  return config;
}

export function matchPattern(value) {
  const url = new URL(value);
  // Firefox match patterns do not support ports. CSP and message validation
  // still use the exact configured origin, including its port.
  return `${url.protocol}//${url.hostname}/*`;
}

export async function configuredManifest(config) {
  const manifest = JSON.parse(await readFile(resolve(extensionRoot, "manifest.json"), "utf8"));
  const dashboardMatch = matchPattern(config.dashboardUrl);
  manifest.host_permissions = [...new Set([matchPattern(config.apiUrl), dashboardMatch])];
  manifest.content_security_policy.extension_pages = `script-src 'self'; object-src 'none'; connect-src ${config.apiUrl}`;
  manifest.content_scripts[0].matches = [dashboardMatch];
  manifest.web_accessible_resources[0].matches = [dashboardMatch];
  return manifest;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await configure({ target: process.argv.includes("--test") ? "development" : "production", test: process.argv.includes("--test") });
}
