import React from 'react';
import {createRoot} from 'react-dom/client';
import LibraryCard from './src/components/LibraryCard';
import {Badge} from './src/components/ui/badge';
import {getCollectionBadgeColor} from './src/constants/colors';
import {Folder,Plus,Search,Bookmark,Layers,Heart,Pencil,Trash2} from 'lucide-react';
import './src/index.css';
const items=[['Design systems handbook','patterns.example','Design','PURPLE'],['A slower weekend','fieldnotes.example','Travel','GREEN'],['Accessible interface patterns','a11y.example','Design','PURPLE'],['A guide to thoughtful typography','typejournal.example','Reading','BLUE'],['Small ideas for better days','journal.example','Reading','BLUE'],['Plan the next adventure','journeys.example','Travel','GREEN']] as const;
createRoot(document.getElementById('root')!).render(<div className="flex h-screen gap-6 p-5 text-[var(--app-ink)]"><aside className="w-56 shrink-0 rounded-3xl border border-[var(--app-mint-border)] bg-[var(--app-reading)] p-5"><img style={{marginBottom:36}} src="/favlock-logo.svg" className="mb-10 w-36"/><p className="app-sidebar-label mb-3">Library</p>{['All Items','Write','Tasks','Readspace','Lists','Favorites'].map((s,i)=><div key={s} className={'mb-2 flex items-center gap-3 rounded-xl p-3 '+(!i?'bg-[var(--app-mint)] text-[var(--app-primary)]':'')}><Layers size={17}/>{s}</div>)}<p className="app-sidebar-label mb-3 mt-8">Collections</p>{['Design','Reading','Travel'].map((s,i)=><div key={s} className="flex items-center gap-3 p-3"><span className="size-3 rounded-full" style={{background:['#b99ad5','#90b9df','#88c5a0'][i]}}/>{s}</div>)}</aside><main className="min-w-0 flex-1 pt-4"><header style={{marginBottom:28}} className="mb-7 flex justify-between"><div><h1 className="text-3xl font-bold">Library</h1><p className="mt-2 text-[var(--app-muted)]">Everything you have saved, in one private workspace</p></div><button className="flex h-11 items-center gap-2 rounded-full bg-[var(--app-primary)] px-5 font-semibold text-white"><Plus size={18}/>Add new</button></header><div style={{height:56,marginBottom:28}} className="mb-7 flex h-14 items-center gap-3 rounded-2xl border border-[var(--app-mint-border)] bg-[var(--app-reading)] px-4 text-[var(--app-muted)]"><Search size={20}/>Search your library</div><h2 className="mb-1 flex items-center gap-2 text-xl font-bold"><Bookmark size={20}/>Recent items</h2><p className="mb-4 text-sm text-[var(--app-muted)]">6 bookmarks</p><div className="grid grid-cols-3 gap-4">{items.map(([title,domain,collection,color])=><LibraryCard key={title} kind="bookmark" collectionColor={color} title={title} onClick={()=>{}} details={<div className="my-6 rounded-xl bg-[var(--app-reading)] p-3 text-sm text-[var(--app-muted)]">{domain}</div>} category={<Badge color={getCollectionBadgeColor(color)}><Folder size={12}/>{collection}</Badge>} actions={<div className="flex gap-3 text-[var(--app-muted)]"><Heart size={15}/><Pencil size={15}/><Trash2 size={15}/></div>}/>)}</div><div style={{marginTop:28}} className="mt-7 rounded-2xl border border-[var(--app-lavender-border)] bg-[var(--app-lavender)] p-5 text-sm">Your bookmarks, documents, tasks, and reading — together in FavLock.</div></main></div>);
